apiVersion: v1
kind: PersistentVolume
metadata:
  name: brand1-pv
  labels:
    app: tracelabel
    org: brand1
    node: peer
    tier: middle
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/brand1-pv


