apiVersion: v1
kind: PersistentVolume
metadata:
  name: tracelabel-db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/tracelabel-db-pv
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracelabel-db-pv-claim
  labels:
    app: tracelabel
    org: tracelabel
    node: peer
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G