apiVersion: v1
kind: Service
metadata:
  name: tracelabel-cli
  labels:
    app: tracelabel
    org: tracelabel
    node: cli
    tier: middle
spec:
  type: NodePort
  ports:
   - port: 7000
     name: listen
     nodePort: 30000
  selector:
    app: tracelabel
    org: tracelabel
    node: cli
    tier: middle


---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cli
  labels:
    app: tracelabel
    org: tracelabel
    node: cli
    tier: middle
spec:
  selector:
    matchLabels:
      app: tracelabel
      org: tracelabel
      node: cli
      tier: middle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tracelabel
        org: tracelabel
        node: cli
        tier: middle
    spec:
      containers:
      - image: ibmblockchain/fabric-tools:1.0.5
        name: fabric-cli
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: ["/bin/bash" ]
        args: ["-c", "sleep 1000000" ]
        env:
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: GOPATH
          value: /opt/gopath
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_LOGGING_LEVEL
          value: debug
        - name: CORE_CHAINCODE_LOGGING_LEVEL
          value: debug
        - name: CORE_PEER_GENERAL_LOCALMSPID
          value: Brand1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/brand1.com/users/Admin@brand1.com/msp
        - name: CORE_CHAINCODE_KEEPALIVE
          value: "10"
        ports:
        - containerPort: 7000
          name: listen
        volumeMounts:
        - name: brand1-admin
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/brand1.com/users/Admin@brand1.com/msp
        - name: brand2-admin
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/brand2.com/users/Admin@brand2.com/msp
        - name: distributors-admin
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/distributors.com/users/Admin@distributors.com/msp

        - name: dockersocket
          mountPath: /host/var/run/docker.sock
        - name: chaincode
          mountPath: /opt/gopath/src/github.com/fabcar
      volumes:
      - name: brand1-admin
        secret:
          secretName: brand1-peer-users
          items:
          - key: sign_cert
            path: signcerts/sign_cert.pem
          - key: sign_key
            path: keystore/sign_key
          - key: ca_cert
            path: cacerts/ca-cert.pem
          - key: admin_cert
            path: admincerts/admin_cert.pem
      - name: brand2-admin
        secret:
          secretName: brand2-peer-users
          items:
          - key: sign_cert
            path: signcerts/sign_cert.pem
          - key: sign_key
            path: keystore/sign_key
          - key: ca_cert
            path: cacerts/ca-cert.pem
          - key: admin_cert
            path: admincerts/admin_cert.pem
      - name: distributors-admin
        secret:
          secretName: distributors-peer-users
          items:
          - key: admin_cert
            path: signcerts/sign_cert.pem
          - key: sign_key
            path: keystore/sign_key
          - key: ca_cert
            path: cacerts/ca-cert.pem
          - key: admin_cert
            path: admincerts/admin_cert.pem
          - key: int_ca_cert
            path: intermediatecerts/int_ca_cert.pem
      - name: chaincode
        configMap:
          name: chaincode
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
