apiVersion: v1
kind: Service
metadata:
  name: brand-2-peer
  labels:
    app: tracelabel
    org: brand-2
    node: peer
    tier: middle
spec:
  type: NodePort
  ports:
    - port: 7051
      name: listen
      nodePort: 30071
    - port: 7053
      name: events
      nodePort: 30073
  selector:
    app: tracelabel
    org: brand-2
    node: peer
    tier: middle


---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: peer
  labels:
    app: tracelabel
    org: brand-2
    node: peer
    tier: middle
spec:
  selector:
    matchLabels:
      app: tracelabel
      org: brand-2
      node: peer
      tier: middle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tracelabel
        org: brand-2
        node: peer
        tier: middle
    spec:
      containers:
      - image: registry.eu-de.bluemix.net/hyperledger/fabric-peer:latest
        name: fabric-peer
        env:
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_ID
          value: peer0.brand2.com
        - name: CORE_LOGGING_PEER
          value: debug
        - name: CORE_CHAINCODE_LOGGING_LEVEL
          value: debug
        - name: CORE_PEER_LOCALMSPID
          value: TraceLabelMSP
        - name: oER_GENERAL_LOCALMSPID
          value: TraceLabelMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/msp/peer/
        - name: CORE_PEER_ADDRESS
          value: peer0.brand2.com:7051
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: CouchDB
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: brand-2-couchdb:5984
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          valueFrom:
                secretKeyRef:
                  name: brand-2-peer-db
                  key: user
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          valueFrom:
                secretKeyRef:
                  name: brand-2-peer-db
                  key: password
        ports:
        - containerPort: 7051
          name: listen
        - containerPort: 7053
          name: evnets
        volumeMounts:
        - name: msp
          mountPath: /etc/hyperledger/msp/peer
          readOnly: true
        - name: users
          mountPath: /etc/hyperledger/msp/users
          readOnly: true
        - name: dockersocket
          mountPath: /host/var/run/docker.sock
      volumes:
      - name: msp
        secret:
          secretName: brand-2-peer-msp
          items:
          - key: sign_cert
            path: signcerts/sign_cert
          - key: private_key
            path: keystore/private_key
          - key: ca.brand2.com-cert.pem
            path: cacerts/ca.brand2.com-cert.pem
          - key: tlsca.brand2.com-cert.pem
            path: tlscacerts/tlsca.brand2.com-cert.pem
          - key: admin_cert
            path: admincerts/admin_cert
      - name: users
        secret:
          secretName: brand-2-peer-users
          items:
          - key: ca_cert
            path: msp/cacerts/ca_cert
          - key: admin_cert
            path: msp/admincerts/admin_cert
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
