apiVersion: v1
kind: Service
metadata:
  name: distributors-peer
  labels:
    app: tracelabel
    org: distributors
    node: peer
    tier: middle
spec:
  type: NodePort
  ports:
    - port: 7051
      name: listen
      nodePort: 30081
    - port: 7053
      name: events
      nodePort: 30083
  selector:
    app: tracelabel
    org: distributors
    node: peer
    tier: middle


---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: peer
  labels:
    app: tracelabel
    org: distributors
    node: peer
    tier: middle
spec:
  selector:
    matchLabels:
      app: tracelabel
      org: distributors
      node: peer
      tier: middle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tracelabel
        org: distributors
        node: peer
        tier: middle
    spec:
      containers:
      - image: registry.eu-de.bluemix.net/hyperledger/fabric-peer:latest
        name: fabric-peer
        env:
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_ID
          value: peer0.distr.tracelabel.com
        - name: CORE_LOGGING_PEER
          value: debug
        - name: CORE_CHAINCODE_LOGGING_LEVEL
          value: debug
        - name: CORE_PEER_LOCALMSPID
          value: DistributorsMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /etc/hyperledger/msp/peer/
        - name: CORE_PEER_ADDRESS
          value: distributors-peer:7051
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: host
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: CouchDB
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: distributors-couchdb:5984
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          valueFrom:
            secretKeyRef:
                name: distributors-peer-db
                key: user
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: distributors-peer-db
              key: password
        ports:
        - containerPort: 7051
          name: listen
        - containerPort: 7053
          name: evnets
        volumeMounts:
        - name: msp
          mountPath: /etc/hyperledger/msp/peer
          readOnly: true
        - name: users
          mountPath: /etc/hyperledger/msp/users
          readOnly: true
        - name: config
          mountPath: /etc/hyperledger/configtx
          readOnly: true
        - name: dockersocket
          mountPath: /host/var/run/docker.sock
      volumes:
      - name: msp
        secret:
          secretName: distributors-peer-msp
          items:
          - key: sign_cert
            path: signcerts/sign_cert.pem
          - key: private_key
            path: keystore/private_key
          - key: ca_cert
            path: cacerts/ca_cert.pem
          - key: int_ca_cert
            path: intermediatecerts/int_ca_cert.pem
          - key: admin_cert
            path: admincerts/admin_cert.pem
      - name: users
        secret:
            secretName: distributors-peer-users
            items:
            - key: ca_cert
              path: admin/msp/cacerts/ca_cert
            - key: int_ca_cert
              path: admin/msp/intermediatecerts/int_ca_cert.pem
            - key: admin_cert
              path: admin/msp/admincerts/admin_cert
            - key: sign_cert
              path: admin/msp/signcerts/sign_cert.pem
            - key: sign_key
              path: admin/msp/keystore/sign_key
      - name: config
        secret:
          secretName: fabric-config
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
