apiVersion: v1
kind: Service
metadata:
  name: brand2-ca
  labels:
    app: tracelabel
    org: brand2
    node: ca
    tier: middle
spec:
  type: NodePort
  ports:
    - port: 7054
      nodePort: 30074
  selector:
    app: tracelabel
    org: brand2
    node: ca
    tier: middle

---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ca
  labels:
    app: tracelabel
    org: brand2
    node: ca
    tier: middle
spec:
  selector:
    matchLabels:
      app: tracelabel
      org: brand2
      node: ca
      tier: middle
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tracelabel
        org: brand2
        node: ca
        tier: middle
    spec:
      containers:
      - image: ibmblockchain/fabric-ca:1.0.5
        name: fabric-ca
        env:
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server/cfg
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca.brand2.com
        ports:
        - containerPort: 7054
          name: ca
        volumeMounts:
        - name: msp
          mountPath: /etc/hyperledger/fabric-ca-server/cfg
          readOnly: true
      volumes:
      - name: msp
        secret:
          secretName: brand2-ca
