apiVersion: v1
kind: PersistentVolume
metadata:
  name: brand2-pv
  labels:
    app: tracelabel
    org: brand2
    node: peer
    tier: middle
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/brand2-pv


